Repository ros2/message_filters, pull requests merged in 2018-11, with the labels that each got.

#13 Add message trait support to frame id of message
  include/message_filters/message_traits.h
Labels: in review

#12 fixed using wrong type of stamp
  src/message_filters/__init__.py
Labels: bug, in review

#14 Add the ability to use raw pointers in Subscriber
  include/message_filters/subscriber.h
  test/test_subscriber.cpp
Labels: enhancement, in review

#16 Fix Duration signature for Windows CI
  test/test_subscriber.cpp
Labels: in progress

#17 Move sensor_msgs to be a test dependency.
  CMakeLists.txt
  package.xml
Labels: in review
